require_relative 'board'
require_relative 'space'
require_relative 'piece'
require_relative 'move'
require_relative 'pieces'
require_relative 'player'
require_relative 'human_player'
require_relative 'coords'
